import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import Showcase from "../components/Showcase";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Showcase />

        {/* <section className="wrapper">
          <h2>header</h2>
        </section> */}
      </main>

      <Footer />
    </>
  );
};

export default Home;
