import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef } from "react";
import Showcase from "../components/Showcase";
import { gsap, Power3 } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { ScrollSmoother } from "gsap/dist/ScrollSmoother";

const Home: NextPage = () => {
  const trigger = useRef(null);
  let comp = useRef(null);
  gsap.registerPlugin(ScrollTrigger);

  useEffect(() => {
    let tl = gsap.timeline({
      scrollTrigger: {
        trigger: trigger.current,
        // pin: true, // pin the trigger element while active
        start: "top center", // when the top of the trigger hits the top of the viewport
        end: "+=500", // end after scrolling 500px beyond the start
        scrub: 1, // smooth scrubbing, takes 1 second to "catch up" to the scrollbar
        // snap: {
        //   snapTo: "labels", // snap to the closest label in the timeline
        //   duration: { min: 0.2, max: 3 }, // the snap animation should be at least 0.2 seconds, but no more than 3 seconds (determined by velocity)
        //   delay: 0.2, // wait 0.2 seconds from the last scroll event before doing the snapping
        //   ease: "power1.inOut", // the ease of the snap animation ("power3" by default)
        // },
      },
    });
    return () => {
      tl.kill();
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Showcase />

        <section className="about" ref={trigger}>
          <h2>Free tools for easy branding and more</h2>
          <section className="wrapper">
            <div className="content" ref={comp}>
              <div className="image">
                <img src="./assets/www-pana.svg" alt="link shortner" />
              </div>
              <aside>
                <h4>Simple and fast URL shortener!</h4>
                <p>
                  Baabar transforms long, ugly looking links from top sites on
                  the internet into nice, memorable, short URLs. just paste the
                  long URL and with the click of a button, your short URL is
                  generated.
                </p>
                <p>
                  Your shortened URLs can be used in publications, documents,
                  advertisements, blogs, forums, instant messages, and other
                  locations.
                </p>

                <button>Shorten Url</button>
              </aside>
            </div>

            <div className="content">
              <aside>
                <h4>Fully customizable QR code</h4>
                <p>
                  Add editable and trackable QR Codes on anything you want with
                  full branding and customization feature
                </p>
                <p>
                  A QR code is a two dimensional barcode that stores information
                  in black and white dots (called data pixels or “QR code
                  modules”). Besides the black and white version, you can also
                  create a colored QR code. For these codes to work without
                  problems, make sure the contrast is sufficient and the result
                  is not a negative (in terms of color). To make your QR code
                  even better, you can also get a QR code with logo.
                </p>
                <div>
                  <button>Generate</button>
                  <button>Scan</button>
                </div>
              </aside>
              <div className="image">
                <img src="./assets/QR Code-pana.svg" alt="qr code" />
              </div>
            </div>
          </section>
        </section>
      </main>
    </>
  );
};

export default Home;
